#!/bin/bash
#SBATCH --partition=dgimi-eha
#SBATCH --mem=40G
module load cv-standard
module load jre

cd  /lustre/namk/processing_fq/Senegal/vcf/SNP ### Fixed this

## Annotating bad SNPs
/nfs/work/faw_adaptation/programs/gatk-4.1.2.0/gatk VariantFiltration -R /lustre/namk/processing_fq/splittedref/258.fa -V 258.SNP.vcf.gz --filter-expression "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0" --filter-name "my_snp_filter" -O 258.SNP.annotated.vcf.gz # Check each SNP is good or not.vcf.gz

## Collecting only good (PASS) SNPs
zcat 258.SNP.annotated.vcf.gz | grep -P '#|PASS' | /nfs/work/faw_adaptation/programs/vcftools_0.1.13/bin/vcftools --vcf - --max-missing 0.8 --out 258.SNP.filtered --recode #Perform filtering

#compress the new vcf file
/nfs/work/faw_adaptation/programs/htslib-1.9/bgzip 258.SNP.filtered.recode.vcf
#index the vcf file
/nfs/work/faw_adaptation/programs/htslib-1.9/tabix -p vcf 258.SNP.filtered.SNP.filtered.recode.vcf.gz

